---

- hosts: default
  remote_user: vagrant
  become: yes
  become_method: sudo

  vars:
    mysql_user_home: /root
    mysql_root_password: super-secure-password
    mysql_root_password_update: yes
    mysql_databases:
      - name: customers
        encoding: utf8
        collation: utf8_general_ci
    mysql_users:
      - name: admin
        host: "localhost"
        password: similarly-secure-password
        priv: "customers.*:ALL"

    php_enable_webserver: true
    php_webserver_daemon: "nginx"
    php_enable_php_fpm: true
    php_fpm_listen: "/var/run/php/php7.0-fpm.sock"

    nginx_remove_default_vhost: true
    nginx_vhosts:
      - listen: "80"
        server_name: "_"
        root: "/var/www/phalcon-service-user"
        index: "index.php index.html index.htm"
        extra_parameters: |
          location / {
            try_files $uri $uri/ /index.php?_url=$uri&$args;
          }

          location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO       $fastcgi_path_info;
            fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;
            include fastcgi_params;
          }

          location ~ /\.ht {
              deny all;
          }

    php7_phalcon_enable_for_fpm: true
    php7_phalcon_cphalcon_version: "3.0.x"

  pre_tasks:
    - name: add ansible repo
      apt_repository: repo="ppa:ansible/ansible"
      tags: ansible_latest

    - name: install ansible latest
      apt: name=ansible update_cache=yes state=latest
      tags: ansible_latest

  roles:
    - { role: geerlingguy.mysql, become: yes, tags: ['mysql'] }
    - { role: geerlingguy.nginx, tags: ['nginx'] }
    - { role: geerlingguy.php, tags: ['php'] }
    - { role: geerlingguy.php-mysql, tags: ['php'] }
    - { role: geerlingguy.composer, tags: ['php'] }
    - { role: vkill.php7-phalcon, tags: ['php'] }

  tasks:
    - name: install zip
      apt: name=zip update_cache=yes state=latest

    - name: create sym link to web root
      file: src=/vagrant/ dest=/var/www/phalcon-service-user state=link

    - name: load fixture data into db
      command: php /vagrant/fixture.php

